### PR TITLE
Save options

### PR DESCRIPTION
**Pull request by jcupitt**
This is @angstyloop's PR #15, with a few changes:

- It uses the `GtkDialog` framework to show the dialog window, so `SaveOptions` is a true widget, and a subclass of `GtkDialog`. This saves quite a bit of code, and make it behave more like a regular gtk dialog (so the popup is draggable, for example).
- The dialog (though not all the contents, of course) are defined in a `.ui` file, reducing code a bit more.
- It looks like a regular dialog to callers, saving some code there too.
- I simplified the widget tree somewhat.
- angstyloop's nice introspection code for creating and reading the option widgets is still there.

To do:

- [x] An error and progress bar in the save popup.
- [x] delayed return of the accept response, for long-running saves.
- [x] a couple of small memleaks, with FIXMEs on them
- [x] the filechooser is being destroyed too early, causing a warning
- [x] cleanup and remove most dbg code

### CODE REVIEW

**Comment by jcupitt** [comment]
I think this is all done now.

**Comment by angstyloop** [comment]
Wow! Thanks J!

**Comment by angstyloop** [comment]
Ha ha

the_answer

**Comment by jcupitt** [comment]
OK, let's merge!

**Comment by jcupitt** [comment]
I made a v2.5 release with this improvement. It should be on flathub shortly.

**Pull request merged**
